theme: just-the-docs
name: Dwarf debugger
title: Dwarf
description: Full featured multi arch/os debugger built on top of PyQt5 and frida
baseurl: /Dwarf
icon: /dwarf.png

aux_links:
  "GitHub":
    - "https://github.com/iGio90/Dwarf"
  "Slack":
    - "https://join.slack.com/t/resecret/shared_invite/enQtMzc1NTg4MzE3NjA1LTlkNzYxNTIwYTc2ZTYyOWY1MTQ1NzBiN2ZhYjQwYmY0ZmRhODQ0NDE3NmRmZjFiMmE1MDYwNWJlNDVjZDcwNGE"

color_scheme: "dark"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
